modLoader="javafml"
loaderVersion="[28,)"

[[mods]]
modId="morethingsmod"
version="1.0.0"
displayName="MoreThingsMod"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
authors="Cardian - exe76, MCreator"
description='''
Ajouts de différents items.
'''

[[dependencies.morethingsmod]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.14.4]"
    ordering="NONE"
    side="BOTH"



